#!/bin/bash
# VSM Session Start Hook
# Verifies skill-state.md exists and is readable.
# If invoked from viable-swarm-model context, ensures agent file is loaded.
#
# Event: SessionStart
# Receives JSON via stdin.

set -euo pipefail

# Read JSON payload from stdin
PAYLOAD=$(cat)
SESSION_ID=$(echo "$PAYLOAD" | jq -r '.session_id // "unknown"')
CWD=$(echo "$PAYLOAD" | jq -r '.cwd // "/tmp"')
SOURCE=$(echo "$PAYLOAD" | jq -r '.source // "unknown"')

# Paths
SKILL_STATE="$HOME/vsm/viable-swarm-model/references/skill-state.md"

# Ensure skill-state.md exists; create template if not
if [[ ! -f "$SKILL_STATE" ]]; then
    mkdir -p "$(dirname "$SKILL_STATE")"
    cat > "$SKILL_STATE" << 'TEMPLATE'
# VSM Skill State — Living Self-Model
> Updated by: `session-start.sh` (read), `session-end.sh` (write), `vsm_meta` (append)
> Read by: S5 at Phase 0

## Capability Matrix
| Agent | Domain | Success Rate | Last 3 Scores | Known Failure Modes |
|-------|--------|-------------|---------------|---------------------|
| vsm_backend_coder | Python/FastAPI | — | — | — |
| vsm_frontend_coder | React/TS | — | — | — |
| vsm_security | Auth/GraphQL | — | — | — |
| vsm_auditor | Code review | — | — | — |
| vsm_architect | Design | — | — | — |

## Current Mood
> Updated after every build by vsm_meta
- **Recent pattern**: "No data yet"
- **Domain struggle**: "No data yet"
- **Agent concern**: "No data yet"
- **Risk elevation**: "No data yet"

## Active Mutation Portfolio
| Mutation ID | Target Failure | Applied | Measured Effect | Status |
|-------------|---------------|---------|-----------------|--------|
| — | — | — | — | — |

## Efficiency Baselines
| Metric | Rolling Avg (5 builds) | Last Build | Trend |
|--------|----------------------|------------|-------|
| Agents spawned | — | — | — |
| File writes | — | — | — |
| Session time (min) | — | — | — |
| Context compactions | — | — | — |

## Known Unknowns (with confidence)
| Hypothesis | Confidence | Last Tested | Priority |
|------------|-----------|-------------|----------|
| — | — | — | — |

## Algedonic Telemetry
| Build | Emissions | Heeded | Ignored | Ignored Rate |
|-------|-----------|--------|---------|--------------|
| — | — | — | — | — |

## Temporal Patterns
> Auto-generated by session-end hook after every 3 builds
- **No patterns detected yet** (insufficient data)
TEMPLATE
fi

# Ensure telemetry directories exist
mkdir -p "$HOME/.vsm-telemetry"

# FB26-S5: Auto-extract broker traps and probationary mutations
# Write them to .kimi/session-context.md so S5 cannot miss them
BROKER_FILE="$HOME/vsm/viable-swarm-model/references/knowledge-broker.md"
MUTATION_STATE="$HOME/vsm/viable-swarm-model/references/mutation-state.md"
SESSION_CONTEXT="$CWD/.kimi/session-context.md"

if [[ -d "$CWD/.kimi" && -f "$BROKER_FILE" ]]; then
    mkdir -p "$CWD/.kimi"
    cat > "$SESSION_CONTEXT" << 'CTXHEAD'
# Session Context — Auto-Generated by session-start.sh (FB26-S5)
> This file contains active broker traps and probationary mutations extracted
> at session start. S5 MUST read this file before spawning any agents.

## Active Broker Traps
CTXHEAD

    # Extract traps marked ACTIVE or with recent build IDs
    grep -E "^\| (G[0-9]+|T[0-9]+).*\|.*ACTIVE\|.*FB[0-9]+" "$BROKER_FILE" 2>/dev/null | while IFS= read -r line; do
        echo "- $line" >> "$SESSION_CONTEXT"
    done
    
    # If no active traps found, note it
    if ! grep -q "^| G" "$SESSION_CONTEXT" 2>/dev/null; then
        echo "_No active traps detected or broker format changed._" >> "$SESSION_CONTEXT"
    fi
    
    echo "" >> "$SESSION_CONTEXT"
    echo "## Probationary Mutations" >> "$SESSION_CONTEXT"
    
    if [[ -f "$MUTATION_STATE" ]]; then
        grep -A2 "Status.*probation\|## FB[0-9]+.*probation" "$MUTATION_STATE" 2>/dev/null | head -30 >> "$SESSION_CONTEXT" || echo "_No probationary mutations found._" >> "$SESSION_CONTEXT"
    else
        echo "_mutation-state.md not found._" >> "$SESSION_CONTEXT"
    fi
    
    echo "" >> "$SESSION_CONTEXT"
    echo "## Reminder for S5" >> "$SESSION_CONTEXT"
    echo "Before spawning any agents, verify:" >> "$SESSION_CONTEXT"
    echo "1. plan.md contains '## Active Constraints from Skill State' section" >> "$SESSION_CONTEXT"
    echo "2. Build prompt explicitly references broker traps and probationary mutations" >> "$SESSION_CONTEXT"
    echo "3. Process auditor will score Phase 0 broker read as a compliance check" >> "$SESSION_CONTEXT"
fi

# Write session marker for telemetry tracking
echo "{\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"session_id\":\"$SESSION_ID\",\"cwd\":\"$CWD\",\"source\":\"$SOURCE\",\"event\":\"session_start\"}" >> "$HOME/.vsm-telemetry/sessions.jsonl"

exit 0
