#!/bin/bash
# VSM Session Start Hook
# Verifies skill-state.md exists and is readable.
# If invoked from viable-swarm-model context, ensures agent file is loaded.
#
# Event: SessionStart
# Receives JSON via stdin.

set -euo pipefail

# Read JSON payload from stdin
PAYLOAD=$(cat)
SESSION_ID=$(echo "$PAYLOAD" | jq -r '.session_id // "unknown"')
CWD=$(echo "$PAYLOAD" | jq -r '.cwd // "/tmp"')
SOURCE=$(echo "$PAYLOAD" | jq -r '.source // "unknown"')

# Paths
SKILL_STATE="$HOME/vsm/viable-swarm-model/references/skill-state.md"

# Ensure skill-state.md exists; create template if not
if [[ ! -f "$SKILL_STATE" ]]; then
    mkdir -p "$(dirname "$SKILL_STATE")"
    cat > "$SKILL_STATE" << 'TEMPLATE'
# VSM Skill State — Living Self-Model
> Updated by: `session-start.sh` (read), `session-end.sh` (write), `vsm_meta` (append)
> Read by: S5 at Phase 0

## Capability Matrix
| Agent | Domain | Success Rate | Last 3 Scores | Known Failure Modes |
|-------|--------|-------------|---------------|---------------------|
| vsm_backend_coder | Python/FastAPI | — | — | — |
| vsm_frontend_coder | React/TS | — | — | — |
| vsm_security | Auth/GraphQL | — | — | — |
| vsm_auditor | Code review | — | — | — |
| vsm_architect | Design | — | — | — |

## Current Mood
> Updated after every build by vsm_meta
- **Recent pattern**: "No data yet"
- **Domain struggle**: "No data yet"
- **Agent concern**: "No data yet"
- **Risk elevation**: "No data yet"

## Active Mutation Portfolio
| Mutation ID | Target Failure | Applied | Measured Effect | Status |
|-------------|---------------|---------|-----------------|--------|
| — | — | — | — | — |

## Efficiency Baselines
| Metric | Rolling Avg (5 builds) | Last Build | Trend |
|--------|----------------------|------------|-------|
| Agents spawned | — | — | — |
| File writes | — | — | — |
| Session time (min) | — | — | — |
| Context compactions | — | — | — |

## Known Unknowns (with confidence)
| Hypothesis | Confidence | Last Tested | Priority |
|------------|-----------|-------------|----------|
| — | — | — | — |

## Algedonic Telemetry
| Build | Emissions | Heeded | Ignored | Ignored Rate |
|-------|-----------|--------|---------|--------------|
| — | — | — | — | — |

## Temporal Patterns
> Auto-generated by session-end hook after every 3 builds
- **No patterns detected yet** (insufficient data)
TEMPLATE
fi

# Ensure telemetry directories exist
mkdir -p "$HOME/.vsm-telemetry"

# Write session marker for telemetry tracking
echo "{\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"session_id\":\"$SESSION_ID\",\"cwd\":\"$CWD\",\"source\":\"$SOURCE\",\"event\":\"session_start\"}" >> "$HOME/.vsm-telemetry/sessions.jsonl"

exit 0
